export const countryInfo = {
  "Afghanistan": { "currency": "Afghan afghani", "language": "Pashto, Dari" },
  "Albania": { "currency": "Albanian lek", "language": "Albanian" },
  "Algeria": { "currency": "Algerian dinar", "language": "Arabic" },
  "Andorra": { "currency": "Euro", "language": "Catalan" },
  "Angola": { "currency": "Angolan kwanza", "language": "Portuguese" },
  "Antigua and Barbuda": { "currency": "East Caribbean dollar", "language": "English" },
  "Argentina": { "currency": "Argentine peso", "language": "Spanish" },
  "Armenia": { "currency": "Armenian dram", "language": "Armenian" },
  "Australia": { "currency": "Australian dollar", "language": "English" },
  "Austria": { "currency": "Euro", "language": "German" },
  "Azerbaijan": { "currency": "Azerbaijani manat", "language": "Azerbaijani" },

  "Bahamas": { "currency": "Bahamian dollar", "language": "English" },
  "Bahrain": { "currency": "Bahraini dinar", "language": "Arabic" },
  "Bangladesh": { "currency": "Bangladeshi taka", "language": "Bengali" },
  "Barbados": { "currency": "Barbadian dollar", "language": "English" },
  "Belarus": { "currency": "Belarusian ruble", "language": "Belarusian, Russian" },
  "Belgium": { "currency": "Euro", "language": "Dutch, French, German" },
  "Belize": { "currency": "Belize dollar", "language": "English" },
  "Benin": { "currency": "West African CFA franc", "language": "French" },
  "Bhutan": { "currency": "Bhutanese ngultrum", "language": "Dzongkha" },
  "Bolivia": { "currency": "Boliviano", "language": "Spanish, Quechua, Aymara" },
  "Bosnia and Herzegovina": { "currency": "Convertible mark", "language": "Bosnian, Croatian, Serbian" },
  "Botswana": { "currency": "Botswana pula", "language": "English, Tswana" },
  "Brazil": { "currency": "Brazilian real", "language": "Portuguese" },
  "Brunei": { "currency": "Brunei dollar", "language": "Malay" },
  "Bulgaria": { "currency": "Bulgarian lev", "language": "Bulgarian" },
  "Burkina Faso": { "currency": "West African CFA franc", "language": "French" },
  "Burundi": { "currency": "Burundian franc", "language": "French, Kirundi" },

  "Cabo Verde": { "currency": "Cape Verdean escudo", "language": "Portuguese" },
  "Cambodia": { "currency": "Cambodian riel", "language": "Khmer" },
  "Cameroon": { "currency": "Central African CFA franc", "language": "English, French" },
  "Canada": { "currency": "Canadian dollar", "language": "English, French" },
  "Central African Republic": { "currency": "Central African CFA franc", "language": "French, Sango" },
  "Chad": { "currency": "Central African CFA franc", "language": "French, Arabic" },
  "Chile": { "currency": "Chilean peso", "language": "Spanish" },
  "China": { "currency": "Chinese yuan", "language": "Chinese (Mandarin)" },
  "Colombia": { "currency": "Colombian peso", "language": "Spanish" },
  "Comoros": { "currency": "Comorian franc", "language": "Arabic, French, Comorian" },
  "Congo (Brazzaville)": { "currency": "Central African CFA franc", "language": "French" },
  "Congo (Kinshasa)": { "currency": "Congolese franc", "language": "French, Lingala, Kikongo, Swahili, Tshiluba" },
  "Costa Rica": { "currency": "Costa Rican colón", "language": "Spanish" },
  "Croatia": { "currency": "Euro", "language": "Croatian" },
  "Cuba": { "currency": "Cuban peso", "language": "Spanish" },
  "Cyprus": { "currency": "Euro", "language": "Greek, Turkish" },
  "Czechia": { "currency": "Czech koruna", "language": "Czech" },

  "Denmark": { "currency": "Danish krone", "language": "Danish" },
  "Djibouti": { "currency": "Djiboutian franc", "language": "Arabic, French" },
  "Dominica": { "currency": "East Caribbean dollar", "language": "English" },
  "Dominican Republic": { "currency": "Dominican peso", "language": "Spanish" },

  "Ecuador": { "currency": "United States dollar", "language": "Spanish" },
  "Egypt": { "currency": "Egyptian pound", "language": "Arabic" },
  "El Salvador": { "currency": "United States dollar, Bitcoin", "language": "Spanish" },
  "Equatorial Guinea": { "currency": "Central African CFA franc", "language": "Spanish, French, Portuguese" },
  "Eritrea": { "currency": "Eritrean nakfa", "language": "Tigrinya, Arabic, English" },
  "Estonia": { "currency": "Euro", "language": "Estonian" },
  "Eswatini": { "currency": "Swazi lilangeni, South African rand", "language": "Swazi, English" },
  "Ethiopia": { "currency": "Ethiopian birr", "language": "Amharic" },

  "Fiji": { "currency": "Fijian dollar", "language": "English, Fijian, Hindi" },
  "Finland": { "currency": "Euro", "language": "Finnish, Swedish" },
  "France": { "currency": "Euro", "language": "French" },

  "Gabon": { "currency": "Central African CFA franc", "language": "French" },
  "Gambia": { "currency": "Gambian dalasi", "language": "English" },
  "Georgia": { "currency": "Georgian lari", "language": "Georgian" },
  "Germany": { "currency": "Euro", "language": "German" },
  "Ghana": { "currency": "Ghanaian cedi", "language": "English" },
  "Greece": { "currency": "Euro", "language": "Greek" },
  "Grenada": { "currency": "East Caribbean dollar", "language": "English" },
  "Guatemala": { "currency": "Guatemalan quetzal", "language": "Spanish" },
  "Guinea": { "currency": "Guinean franc", "language": "French" },
  "Guinea-Bissau": { "currency": "West African CFA franc", "language": "Portuguese" },
  "Guyana": { "currency": "Guyanese dollar", "language": "English" },

  "Haiti": { "currency": "Haitian gourde", "language": "French, Haitian Creole" },
  "Honduras": { "currency": "Honduran lempira", "language": "Spanish" },
  "Hungary": { "currency": "Hungarian forint", "language": "Hungarian" },

  "Iceland": { "currency": "Icelandic króna", "language": "Icelandic" },
  "India": { "currency": "Indian rupee", "language": "Hindi, English" },
  "Indonesia": { "currency": "Indonesian rupiah", "language": "Indonesian" },
  "Iran": { "currency": "Iranian rial", "language": "Persian (Farsi)" },
  "Iraq": { "currency": "Iraqi dinar", "language": "Arabic, Kurdish" },
  "Ireland": { "currency": "Euro", "language": "English, Irish" },
  "Israel": { "currency": "Israeli new shekel", "language": "Hebrew, Arabic" },
  "Italy": { "currency": "Euro", "language": "Italian" },
  "Ivory Coast": { "currency": "West African CFA franc", "language": "French" },

    "Jamaica": { "currency": "Jamaican dollar", "language": "English" },
  "Japan": { "currency": "Japanese yen", "language": "Japanese" },
  "Jordan": { "currency": "Jordanian dinar", "language": "Arabic" },

  "Kazakhstan": { "currency": "Kazakhstani tenge", "language": "Kazakh, Russian" },
  "Kenya": { "currency": "Kenyan shilling", "language": "Swahili, English" },
  "Kiribati": { "currency": "Australian dollar", "language": "English, Gilbertese" },
  "Kuwait": { "currency": "Kuwaiti dinar", "language": "Arabic" },
  "Kyrgyzstan": { "currency": "Kyrgyzstani som", "language": "Kyrgyz, Russian" },

  "Laos": { "currency": "Lao kip", "language": "Lao" },
  "Latvia": { "currency": "Euro", "language": "Latvian" },
  "Lebanon": { "currency": "Lebanese pound", "language": "Arabic" },
  "Lesotho": { "currency": "Lesotho loti, South African rand", "language": "Sesotho, English" },
  "Liberia": { "currency": "Liberian dollar", "language": "English" },
  "Libya": { "currency": "Libyan dinar", "language": "Arabic" },
  "Liechtenstein": { "currency": "Swiss franc", "language": "German" },
  "Lithuania": { "currency": "Euro", "language": "Lithuanian" },
  "Luxembourg": { "currency": "Euro", "language": "Luxembourgish, French, German" },

  "Madagascar": { "currency": "Malagasy ariary", "language": "Malagasy, French" },
  "Malawi": { "currency": "Malawian kwacha", "language": "English, Chichewa" },
  "Malaysia": { "currency": "Malaysian ringgit", "language": "Malay" },
  "Maldives": { "currency": "Maldivian rufiyaa", "language": "Dhivehi" },
  "Mali": { "currency": "West African CFA franc", "language": "French" },
  "Malta": { "currency": "Euro", "language": "Maltese, English" },
  "Marshall Islands": { "currency": "United States dollar", "language": "Marshallese, English" },
  "Mauritania": { "currency": "Mauritanian ouguiya", "language": "Arabic" },
  "Mauritius": { "currency": "Mauritian rupee", "language": "English, French" },
  "Mexico": { "currency": "Mexican peso", "language": "Spanish" },
  "Micronesia": { "currency": "United States dollar", "language": "English" },
  "Moldova": { "currency": "Moldovan leu", "language": "Romanian" },
  "Monaco": { "currency": "Euro", "language": "French" },
  "Mongolia": { "currency": "Mongolian tögrög", "language": "Mongolian" },
  "Montenegro": { "currency": "Euro", "language": "Montenegrin" },
  "Morocco": { "currency": "Moroccan dirham", "language": "Arabic, Berber" },
  "Mozambique": { "currency": "Mozambican metical", "language": "Portuguese" },
  "Myanmar": { "currency": "Myanmar kyat", "language": "Burmese" },

  "Namibia": { "currency": "Namibian dollar, South African rand", "language": "English" },
  "Nauru": { "currency": "Australian dollar", "language": "Nauruan, English" },
  "Nepal": { "currency": "Nepalese rupee", "language": "Nepali" },
  "Netherlands": { "currency": "Euro", "language": "Dutch" },
  "New Zealand": { "currency": "New Zealand dollar", "language": "English, Māori" },
  "Nicaragua": { "currency": "Nicaraguan córdoba", "language": "Spanish" },
  "Niger": { "currency": "West African CFA franc", "language": "French" },
  "Nigeria": { "currency": "Nigerian naira", "language": "English" },
  "North Korea": { "currency": "North Korean won", "language": "Korean" },
  "North Macedonia": { "currency": "Macedonian denar", "language": "Macedonian" },
  "Norway": { "currency": "Norwegian krone", "language": "Norwegian" },

  "Oman": { "currency": "Omani rial", "language": "Arabic" },

  "Pakistan": { "currency": "Pakistani rupee", "language": "Urdu, English" },
  "Palau": { "currency": "United States dollar", "language": "Palauan, English" },
  "Panama": { "currency": "Balboa, United States dollar", "language": "Spanish" },
  "Papua New Guinea": { "currency": "Papua New Guinean kina", "language": "English, Tok Pisin, Hiri Motu" },
  "Paraguay": { "currency": "Paraguayan guaraní", "language": "Spanish, Guaraní" },
  "Peru": { "currency": "Peruvian sol", "language": "Spanish, Quechua, Aymara" },
  "Philippines": { "currency": "Philippine peso", "language": "Filipino, English" },
  "Poland": { "currency": "Polish złoty", "language": "Polish" },
  "Portugal": { "currency": "Euro", "language": "Portuguese" },

  "Qatar": { "currency": "Qatari riyal", "language": "Arabic" },

  "Romania": { "currency": "Romanian leu", "language": "Romanian" },
  "Russia": { "currency": "Russian ruble", "language": "Russian" },
  "Rwanda": { "currency": "Rwandan franc", "language": "Kinyarwanda, English, French" },

  "Saint Kitts and Nevis": { "currency": "East Caribbean dollar", "language": "English" },
  "Saint Lucia": { "currency": "East Caribbean dollar", "language": "English" },
  "Saint Vincent and the Grenadines": { "currency": "East Caribbean dollar", "language": "English" },
  "Samoa": { "currency": "Samoan tālā", "language": "Samoan, English" },
  "San Marino": { "currency": "Euro", "language": "Italian" },
  "Sao Tome and Principe": { "currency": "São Tomé and Príncipe dobra", "language": "Portuguese" },
  "Saudi Arabia": { "currency": "Saudi riyal", "language": "Arabic" },
  "Senegal": { "currency": "West African CFA franc", "language": "French" },
  "Serbia": { "currency": "Serbian dinar", "language": "Serbian" },
  "Seychelles": { "currency": "Seychellois rupee", "language": "Seychellois Creole, English, French" },
  "Sierra Leone": { "currency": "Sierra Leonean leone", "language": "English" },
  "Singapore": { "currency": "Singapore dollar", "language": "English, Malay, Mandarin, Tamil" },
  "Slovakia": { "currency": "Euro", "language": "Slovak" },
  "Slovenia": { "currency": "Euro", "language": "Slovene" },
  "Solomon Islands": { "currency": "Solomon Islands dollar", "language": "English" },
  "Somalia": { "currency": "Somali shilling", "language": "Somali, Arabic" },
  "South Africa": { "currency": "South African rand", "language": "Zulu, Xhosa, Afrikaans, English, and more" },
  "South Korea": { "currency": "South Korean won", "language": "Korean" },
  "South Sudan": { "currency": "South Sudanese pound", "language": "English" },
  "Spain": { "currency": "Euro", "language": "Spanish" },
  "Sri Lanka": { "currency": "Sri Lankan rupee", "language": "Sinhala, Tamil" },
  "Sudan": { "currency": "Sudanese pound", "language": "Arabic, English" },
  "Suriname": { "currency": "Surinamese dollar", "language": "Dutch" },
  "Sweden": { "currency": "Swedish krona", "language": "Swedish" },
  "Switzerland": { "currency": "Swiss franc", "language": "German, French, Italian, Romansh" },
  "Syria": { "currency": "Syrian pound", "language": "Arabic" },

  "Taiwan": { "currency": "New Taiwan dollar", "language": "Mandarin" },
  "Tajikistan": { "currency": "Tajikistani somoni", "language": "Tajik" },
  "Tanzania": { "currency": "Tanzanian shilling", "language": "Swahili, English" },
  "Thailand": { "currency": "Thai baht", "language": "Thai" },
  "Timor-Leste": { "currency": "United States dollar", "language": "Portuguese, Tetum" },
  "Togo": { "currency": "West African CFA franc", "language": "French" },
  "Tonga": { "currency": "Tongan paʻanga", "language": "Tongan, English" },
  "Trinidad and Tobago": { "currency": "Trinidad and Tobago dollar", "language": "English" },
  "Tunisia": { "currency": "Tunisian dinar", "language": "Arabic" },
  "Turkey": { "currency": "Turkish lira", "language": "Turkish" },
  "Turkmenistan": { "currency": "Turkmenistani manat", "language": "Turkmen" },
  "Tuvalu": { "currency": "Australian dollar", "language": "Tuvaluan, English" },

  "Uganda": { "currency": "Ugandan shilling", "language": "English, Swahili" },
  "Ukraine": { "currency": "Ukrainian hryvnia", "language": "Ukrainian" },
  "United Arab Emirates": { "currency": "UAE dirham", "language": "Arabic" },
  "United Kingdom": { "currency": "British pound", "language": "English" },
  "United States of America": { "currency": "United States dollar", "language": "English" },
  "Uruguay": { "currency": "Uruguayan peso", "language": "Spanish" },
  "Uzbekistan": { "currency": "Uzbekistani soʻm", "language": "Uzbek" },

  "Vanuatu": { "currency": "Vanuatu vatu", "language": "Bislama, English, French" },
  "Vatican City": { "currency": "Euro", "language": "Italian, Latin" },
  "Venezuela": { "currency": "Venezuelan bolívar", "language": "Spanish" },
  "Vietnam": { "currency": "Vietnamese đồng", "language": "Vietnamese" },

  "Yemen": { "currency": "Yemeni rial", "language": "Arabic" },

  "Zambia": { "currency": "Zambian kwacha", "language": "English" },
  "Zimbabwe": {
    "currency": "Zimbabwean dollar, US dollar, others",
    "language": "Shona, Ndebele, English, and others"
  }

};
